---
- hosts: all
  become: yes

  vars_filea:
  - vars.yml

  handlers:
    - name: restart "services"
      service: name="{{ item }} state=restarted enabled=yes"
      with_items:
        - service1
        - service2

  pre_tasks:
    - name: <enter details hear>

# Below are some typical ansible tasks that would be included in a playbook delete or amend as appropriate
  tasks:
    - name: <enter details hear>

    - name: Ensure that a Directory exists
      file:
        path: "path to file"
        state: directory
        owner: <some user>
        group: <some group>

    - name: Check if a file exists
      stat:
        path: "path to file"
      register: file_state

    - name: Run a command if the file does not exist
      command: >
        some command here
        chdir=/tmp
        creates="path to file"
      when: not file_state.stat.exists

    - name: Amend contents of file x and set up parameter y
      lineinfile:
        dest: "source file x"
        regexp: "^python style regex"
        line: "line to become"
        state: present
        notify: restart service1

    - name: Amend contents of file with template
      template:
        src: "templates/templatefile.j2"
        dest: "some destintion"
        owner: <some user>
        group: <some group>
        mode: 0644
        notify: restart service2

  post_tasks:
    - name: <enter details hear>
